image: gitpod/workspace-full-vnc
tasks:
  - init: npm install -g @angular/cli && npm install && sudo apt-get install -y --no-install-recommends chromium-browser
  - command: for i in {1..6}; do chmod 600 ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa.pub && ssh-keyscan github.com >> ~/.ssh/known_hosts; sleep 20; done
  - command: git remote set-url origin git@github.com:cloudlabstudent01/cloudlabstudent01-AG-TC-PF.git && sed "s/\r$//" commit-command.sh | bash
  - command: sleep 30;code --install-extension Revaturepro-non-prod.revature-angular-labs-non-prod
